### ISSUE TITLE
Dot at the end of hostname

### ISSUE THREAD

**Issue by wangqiang1208** [KimNorgaard/validates_hostname#3] opened 2015-01-08 13:00 UTC
'example.org.'  the hostname end with dot are considered to be valid now

which should not be valid.. as RFC document says:

> RFC952: Note that periods(.) are only allowed when they serve to delimit components of "domain style names".

**Comment by KimNorgaard** [comment] 2015-01-12 13:41
This is by design (RFC 1034):

> When a user needs to type a domain name, the length of each label is
> omitted and the labels are separated by dots (".").  Since a complete
> domain name ends with the root label, this leads to a printed form which
> ends in a dot.  We use this property to distinguish between:
>  
>    - a character string which represents a complete domain name
>      (often called "absolute").  For example, "poneria.ISI.EDU."
>  
>    - a character string that represents the starting labels of a
>      domain name which is incomplete, and should be completed by
>      local software using knowledge of the local domain (often
>      called "relative").  For example, "poneria" used in the
>      ISI.EDU domain.

**Comment by wangqiang1208** [comment] 2015-01-12 13:43
Ok, Thanks !

But name like <code>example.org......</code> is valid also, Can we provide an option to disable this ?

**Comment by KimNorgaard** [comment] 2015-01-12 14:13
Yes, that is not be design :-)

The expected behavior should be that:

1) An option - :allow_root_label (default: false) should be added. This controls wether to check for the presence of a single dot at the end of the domain name.
2) Consecutive dots anywhere in a domain name should never be permitted.

Is this what you are looking for?

**Comment by wangqiang1208** [comment] 2015-01-12 14:15
Exactly, If you don't have time I can do this through PR  for you  :-)

**Comment by KimNorgaard** [comment] 2015-01-12 16:53
Should be fixed with latest commit. Please confirm that it works in your end.

If it does, I'll bump the version on ruby-gems.

**Comment by wangqiang1208** [comment] 2015-01-12 17:53
Many thanks !

I confirm  that it works for me, I also tested this option <code> allow_root_label</code>, works fine.

**Closed** 2015-01-12 18:31 UTC
